version: '{build}'
clone_depth: 1
stack: node 8

image:
  - Visual Studio 2017
  - Ubuntu

branches:
  only:
    - master
    - dev

configuration:
  - Release

init:
  - git config --global core.autocrlf true

before_build:
  - ps: node --version
  - ps: npm --version
  - ps: dotnet --info
  - ps: "Get-ChildItem Env:"
  - ps: ./init_solution.ps1

build_script:
  - ps: ./build/build.ps1

test_script:
  - ps: dotnet test ./tests/OneDas.Core.Tests -c $Env:Configuration /p:BuildProjectReferences=false

artifacts:
  - path: ./artifacts/packages/**/*.nupkg
  - path: ./artifacts/msi/**/*.msi

deploy:

# GitHub (master)
  - provider: GitHub
    force_update: true
    auth_token:
      secure: Ssl8rHF6345+qU9lhUQlHRx0Ta4e6UXIQM3SEpDpjR4+WcpMJM3TvQ5gUWjwf6jQ
    artifact: /.*\.msi/
    on:
      branch: master
      CI_WINDOWS: true
      APPVEYOR_REPO_TAG: true

# NuGet (master)
  - provider: NuGet
    server: https://www.nuget.org/api/v2/package
    api_key:
      secure: Z+/E7/8k05NePoUmHdtw/sTn6GSM+0e7ko6A02/rBjm6K9wVTYNekWHvSv7GEBtC
    skip_symbols: true
    artifact: /.*\.nupkg/ 
    on:
      branch: master
      CI_WINDOWS: true
      APPVEYOR_REPO_TAG: true

# MyGet (dev)
  - provider: NuGet
    server: https://www.myget.org/F/onedas/api/v2/package
    api_key:
      secure: DVadlPknnKPMR4F2+3VqeU7BFFmtLcXDHzkySA590MqQNIdzbx8HRuaPwDVbHRqX
    skip_symbols: true
    artifact: /.*\.nupkg/ 
    on:
      branch: dev
      CI_WINDOWS: true